### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by jhorsley** [anthonime/gwt-d3#45]
I couldn't see what license the project is operating under. d3.js is BSD is gwt-d3 the same given it's just a wrapper around d3?

**Comment by anthonime** [comment]
Thank you for pointing this out.

First, the official repo for gwt-d3 is here (please add report the issue
there):
https://github.com/gwtd3/gwt-d3

But to answer your question, I must admit that I have neglected the license
aspect of the project until now, and I'm a newbie regarding this topic...

I guess as you said, I should use the same license as d3.js...

2013/6/19 jhorsley notifications@github.com

> I couldn't see what license the project is operating under. d3.js is BSD
> is gwt-d3 the same given it's just a wrapper around d3?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anthonime/gwt-d3/issues/45
> .

## 

_Anthoni Schiochet_
+33 (0)6 51 81 11 87

**Comment by anthonime** [comment]
In the mean time,

I just added the BSD license in the repo https://github.com/gwtd3/gwt-d3

thank you again for your feedback.

Are you interested in gwt-d3 ?

2013/6/19 Anthoni Schiochet schiochetanthoni@gmail.com

> Thank you for pointing this out.
> 
> First, the official repo for gwt-d3 is here (please add report the issue
> there):
> https://github.com/gwtd3/gwt-d3
> 
> But to answer your question, I must admit that I have neglected the
> license aspect of the project until now, and I'm a newbie regarding this
> topic...
> 
> I guess as you said, I should use the same license as d3.js...
> 
> 2013/6/19 jhorsley notifications@github.com
> 
> > I couldn't see what license the project is operating under. d3.js is BSD
> > is gwt-d3 the same given it's just a wrapper around d3?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/anthonime/gwt-d3/issues/45
> > .
> 
> ## 
> 
> _Anthoni Schiochet_
> +33 (0)6 51 81 11 87

## 

_Anthoni Schiochet_
+33 (0)6 51 81 11 87

**Comment by jhorsley** [comment]
Thanks for responding so quickly!! I've created https://github.com/gwtd3/gwt-d3/issues/46 so will close this one
